name: Legacy-Client E2E
on: workflow_dispatch
jobs:
  E2E:
    name: Test the legacy did client against the on-chain program on Solana ${{ matrix.solana }}, Node ${{ matrix.node }}, Rust ${{ matrix.rust }}, and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['16.x']
        os: [ubuntu-latest]
        solana: ['stable']
        rust: ['stable']

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Rust ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          profile: minimal

      - name: Cache build dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./legacy/program/target
          key: cargo-legacy-build-${{ hashFiles('legacy/program/Cargo.lock') }}

      - name: Cache Solana version
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache
          key: solana-${{ matrix.solana }}

      - name: Install Solana
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/${{ matrix.solana }}/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Build program
        uses: actions-rs/cargo@v1
        with:
          command: build-bpf
          args: --manifest-path legacy/program/Cargo.toml

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Cache node dependencies
        uses: actions/cache@v2
        with:
          path: |
            ./legacy/client/node_modules
          key: yarn-legacy-client-${{ hashFiles('legacy/client/yarn.lock') }}

      - name: Install client dependencies
        run: yarn install
        working-directory: legacy/client

      - name: Test e2e
        run: yarn test-e2e
        working-directory: legacy/client
